### ISSUE TITLE
Add usecase sample for ava

### ISSUE THREAD

**Issue by ragingwind** [kevinsawicki/spectron#10]
I've [tested the code](https://github.com/electron-kr/electron-spectron-showcase/blob/master/test.js) with [ava](https://github.com/sindresorhus/ava) and It worked well. I think, It would be helpful that add sample code for ava to readme.

**Comment by kevinsawicki** [comment]
Sounds good to me.

I've never used ava before so if you have time to open a pull request for this that would be awesome :+1:

**Comment by ragingwind** [comment]
@kevinsawicki I've updated please take a look

**Comment by kevinsawicki** [comment]
Fixed by #11

**Comment by ragingwind** [comment]
Thanks!
