### ISSUE TITLE
Help getting started

### ISSUE THREAD

**Issue by JoshuaBStevens** [kevinsawicki/spectron#12]
I'm trying to use spectron with mocha.  In my beforeEach, I have:
`this.app = new Application({path: "bin/package/pluginContainer.html"});`
`return this.appstart();`
This times out after 2000ms.  What am I doing wrong?  Am I passing the wrong path to Application?  I didn't see a description anywhere of what that path is supposed to point to.

Thanks,
-Josh

**Comment by JoshuaBStevens** [comment]
Sorry, that second line should have been "return this.app.start()", not "return this.appstart()".

**Comment by KevinMartin** [comment]
Based on the README.md, your path is wrong. It should point to the binary of your app:

On Mac:
```
    this.app = new Application({
      path: '/Applications/MyApp.app/Contents/MacOS/MyApp'
    });
```

On Windows, it should be `.cmd` file

**Comment by JoshuaBStevens** [comment]
I don't have a binary for my app.  I run my app via electron.exe.  I tried creating a .cmd file to wrap the call to electron.exe, but that didn't help -- I still get the same error.

**Comment by kevinsawicki** [comment]
@JoshuaBStevens so you'll need to specify the path to electron as the path and specify the path to your app as an argument.

something like the following but with the paths adjusted for your setup:

```js
// Path to Electron
var electronPath = path.join(__dirname, '..', 'node_modules', '.bin', 'electron')
if (process.platform === 'win32') electronPath += '.cmd'

// Path to your application
var appPath = path.join(__dirname, 'bin', 'package')

var app = new Application({
  path: electronPath,
  args: [appPath]
})
app.start()
```

Hope this helps.

**Comment by JoshuaBStevens** [comment]
Thanks, that got me a bit further.  Is there a way to tell it to start the app with the current directory set to a specific folder?  More generally, is there an API reference for the Application class that describes all the properties it supports?  (Sorry if this is a dumb/obvious question, I'm really new to the JS world.)

**Comment by kevinsawicki** [comment]
@JoshuaBStevens All the current options are documented at https://github.com/kevinsawicki/spectron#application

So are you looking to set the current working directory of the started app?

**Comment by JoshuaBStevens** [comment]
Yes, that's what I need to do.  To run my app manually, I go to bin\package and run "electron.exe .".  Using your previous recommendation, I'm able to get electron to start, but it immediately complains about some missing manifest file, which is why I think it probably needs to be started in my package folder.

**Comment by kevinsawicki** [comment]
Can you paste the full error you are seeing?

I can add support for a configurable working directory though.

**Comment by JoshuaBStevens** [comment]
Actually, I think the error ("Host Error: Failed to load manifest file: manifest.json") is not really from electron, it's from a component I'm using in my app.  Regardless, I think the solution is to change the cwd, as manifest.json is present under bin\package.

**Comment by kevinsawicki** [comment]
@JoshuaBStevens there is now a `0.36.1` version that exposes a `cwd` option to the `Application` constructor that can be used to set the working directory of the launched application.

See the `README.md` and/or `CHANGELOG.md` for more details, closing this issue out.

**Comment by JoshuaBStevens** [comment]
Thanks for the quick response!  However, after getting the new version, I'm seeing 'new Application({path: "./xShell-release-windows/electron.exe", args: ["."], cwd: "./bin/package"})' returning null.

**Comment by kevinsawicki** [comment]
@JoshuaBStevens can you share a full code snippet? I'm having trouble reproducing `new Application` returning null.

**Comment by JoshuaBStevens** [comment]
Well, that no longer seems to happen for me either -- I don't know why.  Now it's just timing out (after 2000ms).  Here is my code:

var Application = require("spectron").Application;

describe("foo", () => {
  let app: any;
  
  beforeEach(() => {
    this.app = new Application({path: "./xShell-release-windows/electron.exe", args: ["."], cwd: "./bin/package"});
    return this.app.start();
  })
 
  afterEach(function () {
    if (this.app && this.app.isRunning()) {
      return this.app.stop()
    }
  })
 
  it("should do something", () => { });
});

**Comment by kevinsawicki** [comment]
Does it work if you use absolute paths instead of relative paths?

**Comment by JoshuaBStevens** [comment]
It does work better!  I can see Electron opening with my app's UI.  However, I still get a timeout error for the beforeEach method.

**Comment by myfrndjk** [comment]
Hi,

I have a problem in getting started with spectron.
Can some one help me with this 

https://discuss.atom.io/t/spectron-not-triggering-app/48123

**Comment by AmanChhabra-A746623** [comment]
HI @kevinsawicki @JoshuaBStevens  I have my electron application in another directory and spectron application in some other directory. How can I set path to run electron from spectron application?
