### ISSUE TITLE
Getting userData path

### ISSUE THREAD

**Issue by HR** [kevinsawicki/spectron#16]
How can you get the userData path that's available in electron via
```javascript
app.getPath('userData')
```

**Comment by kevinsawicki** [comment]
I think this should be added to the spectron API but for now you can add your own command helper for it if you want to access it from your tests:

```js
app.client.addCommand('getUserDataPath', function () {
  return this.execute(function () {
    require('electron').remote.app.getPath('userData')
  })
})
```

Then in your specs you could call it via:

```js
app.client.getUserDataPath().then(...)
```
